### ISSUE TITLE
Move more functions into flowz

### ISSUE THREAD

**Issue by PatrickDRusk** [ethanrowe/flowz#10]
Moving additional "known to work" functions into flowz, including relevant API changes.

The unit tests and further documentation for this functions will move shortly thereafter.

**Comment by ethanrowe** [comment]
@PatrickDRusk do you think this should be going into the next release?  I was aiming for Tuesday afternoon or Wednesday morning.

**Comment by PatrickDRusk** [comment]
Yes. Though there are not yet unit tests for the functions, the script that I have been refactoring along the way continues to function properly with those moved/renamed functions.

**Comment by ethanrowe** [comment]
Okay, I'm marking this as done, then, since it's integrated into ``develop`` for the next release as intended.
