### ISSUE TITLE
Observe the values on a channel

### ISSUE THREAD

**Issue by ethanrowe** [ethanrowe/flowz#14]
For purposes of logging, metrics, debugging, etc., it's helpful to be able to watch the values on a channel without doing anything to those values.

So what I want is an ``ObserveChannel``, that, given an input channel and some callable, passes each input channel value (on read) to the callable, and then emits that input channel value unchanged.

Thus I can observe the values in the channel and react to them (with side effects!  Hoo boy!  Yippee!  Skippee!), without "interfering" with them.

For instance:

```python
a = IterChannel(range(5))
# Will emit 0, 1, 4, 9, 16
b = a.map(lambda i: i ** 2)
```

versus the functionally equivalent (but different in terms of I/O)

```python
from __future__ import print_function
a = IterChannel(range(5))
# Will emit 0, 1, 4, 9, 16, but will also print them.
b = a.map(lambda i: i ** 2).observe(print)
```

**Comment by ethanrowe** [comment]
I believe this is under control.  For instance:

```python
from __future__ import print_function
from flowz.channels import *
from flowz.app import Flo 

def build(length=5):
    c = IterChannel(range(length))
    return c, c.observe(print)

def run(c):
    Flo([c.map(lambda v: print("Out: %s" % str(v)))]).run()

run(build()[0])
# Out: 0
# Out: 1
# Out: 2
# Out: 3
# Out: 4

run(build()[1])
# 0
# Out: 0
# 1
# Out: 1
# 2
# Out: 2
# 3
# Out: 3
# 4
# Out: 4
```

**Comment by PatrickDRusk** [comment]
+1
