### ISSUE TITLE
Fix exception handling to keep tracebacks

### ISSUE THREAD

**Issue by PatrickDRusk** [ethanrowe/flowz#24]
The current mechanism propagating exception via the futures in channels is susceptible to losing traceback information in Python 2.x. The use of set_exc_info() instead of set_exception() should avoid this, at a cost of potentially generating (but not displaying) some tracebacks that never end up getting shown if the exception is caught and handled in other code.

**Comment by ethanrowe** [comment]
Yep.  I think we'll do a python 3 compatibility sweep in a subsequent release, so for 0.3.0, a python-2 solution is okay.
