### ISSUE TITLE
ZipChannel should clear out all input channels

### ISSUE THREAD

**Issue by ethanrowe** [ethanrowe/flowz#30]
The `flowz.channels.core.ZipChannel` implementation currently:
- Pulls each input channel item in turn
- Issues its `ChannelDone` exception as soon as _any_ input channel issues `ChannelDone`, leaving the other channels (that are not necessarily yet exhausted) alone from that point forward.

This results in the eventual `ChannelDone` exceptions of those unconsumed inputs staying around within the tornado `IOLoop`, and thus you get a pile of warnings at the end of your app when the `IOLoop` stops.

We should consume those inputs or otherwise clear those exceptions to shut this up, and also to make sure any memory consumption associated with those futures is released.

**Comment by ethanrowe** [comment]
In the case with zip, see that after a few runs, I get a bunch of warnings.

```python
>>> from flowz import channels
>>> from flowz import app
>>> i = lambda x: channels.IterChannel(range(x))
>>> app.Flo([i(3).zip(i(10), i(10))]).run()
>>> app.Flo([i(3).zip(i(10), i(10))]).run()
>>> app.Flo([i(3).zip(i(10), i(10))]).run()
2016-07-05 17:18:21,224 ERROR #35 140688636077888 tornado.application Future exception was never retrieved: ChannelDone: Channel is done
2016-07-05 17:18:21,224 ERROR #35 140688636077888 tornado.application Future exception was never retrieved: ChannelDone: Channel is done
2016-07-05 17:18:21,225 ERROR #35 140688636077888 tornado.application Future exception was never retrieved: ChannelDone: Channel is done
2016-07-05 17:18:21,225 ERROR #35 140688636077888 tornado.application Future exception was never retrieved: ChannelDone: Channel is done
```

But then in the same session, I consume similar channels with no zip usage, and I don't get the noise.

```python
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> app.Flo([i(3), i(3), i(3)]).run()
>>> 
```

**Comment by ethanrowe** [comment]
It's a product of the `tornado.concurrent.Future` object and the way it deals with exceptions.  It happens that the way we do zip is likely to trip this behavior.

See:
https://github.com/tornadoweb/tornado/blob/9f723211348f14a650f87c9c991260b387b18cb0/tornado/concurrent.py#L126-L129

And...
https://github.com/tornadoweb/tornado/blob/9f723211348f14a650f87c9c991260b387b18cb0/tornado/concurrent.py#L328-L341

**Comment by PatrickDRusk** [comment]
So it only cares about future exceptions that haven't been retrieved, right? If a future that would resolve fine is never queried, that won't cause a problem?

**Comment by ethanrowe** [comment]
Right, because it's on the `Future` itself, when it's GCed.  The `Future` knows if it has been "read", so if it is destroyed without having been read, and there's a traceback on it, you get this error logged.

**Comment by ethanrowe** [comment]
Not going to delay the 0.4.0 release for this known issue.

**Comment by PatrickDRusk** [comment]
I thought this problem was resolved, but I see the changes still sitting in "develop". Is there a plan to include this in a release?

**Comment by ethanrowe** [comment]
I didn't see it as a particularly urgent matter and thought we might
accumulate more stuff before bundling up a release.  But I don't have a
problem doing a release sooner.

**Comment by PatrickDRusk** [comment]
No rush.

In fact, my preference would be that you add the new decorator that does the channel_property thing that returns a method, and then build a release. :)
