### ISSUE TITLE
Add decorator for method based channel provision

### ISSUE THREAD

**Issue by PatrickDRusk** [ethanrowe/flowz#41]
The current ChannelManager mechanism that uses a @channel_property to create a property that provisions (creating or teeing) a channel has turned out to be tricky to use without still creating excess tees. We have discussed a very similar mechanism that will leave the decorated method as a method, not a property, easing the process of constructing trees of channels without excess tees.

**Comment by ethanrowe** [comment]
On it.

**Comment by ethanrowe** [comment]
This will close when a new release happens.
