### ISSUE TITLE
WrappedArtifact.__getattr__ needs a guard against infinite recursion

### ISSUE THREAD

**Issue by PatrickDRusk** [ethanrowe/flowz#7]
The WrappedArtifact.__getattr__ method looks like:
```Python
    def __getattr__(self, attr):
        return getattr(self.value, attr)
```
If that is called before there is a self.value attribute, it gets into infinite recursion (throwing an exception eventually).

**Comment by ethanrowe** [comment]
@PatrickDRusk this one was settled, right?

**Comment by PatrickDRusk** [comment]
Yes. The commit listed above fixed it.
